[theme]
theme = "solarized-dark"

[theme.overrides]
idle_bg = "#fbf1f2"
idle_fg = "#8b8198"
info_bg = "#06969A"
info_fg = "#fbf1f2"
good_bg = "#A3B367"
good_fg = "#fbf1f2"
warning_bg = "#DCB16C"
warning_fg = "#fbf1f2"
critical_bg = "#DA627D"
critical_fg = "#fbf1f2"

[icons]
icons = "awesome6"

[[block]]
block = "battery"
device = "/sys/class/power_supply/macsmc-battery"
missing_format = ""

[[block]]
block = "bluetooth"
mac = "10:7C:61:27:9F:A8"
disconnected_format = ""

[[block]]
block = "cpu"

[[block]]
block = "speedtest"
format = " ^icon_net_down $speed_down ^icon_net_up $speed_up "

[[block]]
block = "sound"

[[block]]
block = "time"
timezone = "Europe/Istanbul"
format = " $icon $timestamp.datetime(f:'%F %T', l:en_US) "
